import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import DaisyNav from "@/components/DaisyNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <DaisyNav />
        <div className="lg:w-[1120px] md:w-[calc(836px-64px)] mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
